# Generated by Django 4.2.2 on 2023-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='board',
            new_name='board_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='column',
            new_name='column_id',
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board_id', 'position')},
        ),
    ]
